# Check https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html for an
# overview of the template's contents!
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NB-IoT Soil Monitoring (somon)

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  somon:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: bootstrap
      Runtime: provided.al2023
       # Check https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html for more info!
      Tracing: PassThrough
      Events:
        CatchAll:
          # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Type: Api
          Properties:
            Path: /somon
            Method: POST
      # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Environment:
        Variables:
          LOG_LEVEL: DEBUG
          LOCAL: yes
    Metadata:
      BuildMethod: makefile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  somonAPI:
    Description: "API Gateway endpoint URL for Prod environment for somon API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/somon/"
  somonFunction:
    Description: "somon Function ARN"
    Value: !GetAtt somon.Arn
  somonIamRole:
    Description: "Implicit IAM Role created for the somon Function"
    Value: !GetAtt somonFunctionRole.Arn
